env:
  es2021: true
  node: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
rules:
  '@typescript-eslint/indent': 
    - error 
    - tab
  linebreak-style:
    - error
    - unix
  '@typescript-eslint/quotes':
    - error
    - single
  semi:
    - error
    - never
  object-curly-spacing: 
    - error
    - never
  '@typescript-eslint/object-curly-spacing':
    - error
    - never
  no-tabs:
    - off 
  '@typescript-eslint/space-before-function-paren':
    - off
