env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  eqeqeq: 
    - error
    - always
  space-before-function-paren: 
    - error
    - never

  # overrides for typescript
  object-curly-spacing:
    - off
  no-return-await: 
    - off


  # typescript specific rules
  '@typescript-eslint/object-curly-spacing':
    - error
    - never
  '@typescript-eslint/ban-ts-comment':
    - warn
    - always
  '@typescript-eslint/no-floating-promises':
    - error
    - ignoreVoid: true
      ignoreIIFE: true
  '@typescript-eslint/array-type':
    - error
    - type: 'array'

  '@typescript-eslint/await-thenable': 
    - error
  '@typescript-eslint/return-await': 
    - error
    - in-try-catch
